openapi: 3.1.0

info:
  title: University app
  version: 1.0.0
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of University app

tags:
  - name: Students
    description: Operations with students.
  - name: Auth
    description: Auth operations.

servers:
  - url: http://127.0.0.1:8080

paths:

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
